# Generated by Django 4.2.1 on 2023-06-12 08:35

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('desc', models.TextField(max_length=1000, verbose_name='Опис')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('image', models.ImageField(upload_to=main_page.utils.get_file_name_id, verbose_name='Зображення')),
                ('tab_name', models.CharField(default='Скачати актуальний каталог', max_length=70, verbose_name='Текст кнопки')),
                ('cat_url', models.URLField(blank=True, default='"https://drive.google.com/file/d/1Hcbe8G_xCCVQkd-r-uhrJQ95EX2FsaFl/view', verbose_name='Посилання на актуальний каталог')),
            ],
            options={
                'verbose_name_plural': 'Про нас',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон 1')),
                ('email', models.CharField(max_length=50, verbose_name='Пошта ')),
                ('fb_url', models.URLField(blank=True, default='https://www.facebook.com/', verbose_name='Посилання на facebook')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/', verbose_name='Посилання на youtube')),
                ('in_url', models.URLField(blank=True, default='https://www.instagram.com/', verbose_name='Посилання на instagram')),
            ],
            options={
                'verbose_name_plural': 'Контакти',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=250)),
                ('subject', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_processing', models.DateField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': "Зворотній зв'язок",
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва слайду')),
                ('position', models.SmallIntegerField(verbose_name='Позиція')),
                ('image', models.ImageField(upload_to=main_page.utils.get_file_name_id, verbose_name='Зображення')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('h_1', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Опис')),
                ('tab', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('tab_url', models.URLField(blank=True, verbose_name='Посилання з кнопки')),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_processing', models.DateField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Підписка на email розсилку',
                'ordering': ('-date',),
            },
        ),
    ]
