# Generated by Django 4.2.1 on 2023-06-06 16:22

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_contacts_contactus_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('desc', models.TextField(max_length=1000, verbose_name='Опис')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('image', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення')),
                ('tab_name', models.CharField(default='Скачати актуальний каталог', max_length=70, verbose_name='Текст кнопки')),
                ('cat_url', models.URLField(blank=True, default='"https://drive.google.com/file/d/1Hcbe8G_xCCVQkd-r-uhrJQ95EX2FsaFl/view', verbose_name='Посилання на актуальний каталог')),
            ],
            options={
                'verbose_name_plural': 'Про нас',
                'ordering': ('title',),
            },
        ),
    ]
