# Generated by Django 4.2.1 on 2023-06-15 17:15

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_baner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baner',
            name='image_3',
            field=models.ImageField(upload_to=main_page.utils.get_file_name_id, verbose_name='Зображення банер 1'),
        ),
        migrations.AlterField(
            model_name='baner',
            name='image_4',
            field=models.ImageField(upload_to=main_page.utils.get_file_name_id, verbose_name='Зображення банер 2'),
        ),
    ]
