# Generated by Django 4.2.1 on 2023-06-06 16:25

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to=main_page.utils.get_file_name_id, verbose_name='Зображення'),
        ),
    ]
