# Generated by Django 4.2.1 on 2023-06-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_photo_subproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_main_page',
            field=models.BooleanField(default=True, verbose_name='Відображення на головній'),
        ),
    ]
