# Generated by Django 4.2.1 on 2023-06-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_category_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_main_page',
            field=models.BooleanField(default=False, verbose_name='Відображення на головній'),
        ),
    ]
