# Generated by Django 4.2.1 on 2023-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_options_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Н', 'Немає в наявності'), ('В', 'В наявності'), ('П', 'Під замовлення 2-3 дні'), ('C', 'Скоро в наявності')], default='Н', max_length=1),
        ),
    ]
