# Generated by Django 4.2.1 on 2023-06-09 19:46

from django.db import migrations, models
import django.db.models.deletion
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Застосування'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics_gender',
            field=models.CharField(blank=True, choices=[('Ч', 'Чоловіча'), ('Ж', 'Жіноча'), ('У', 'Унісекс')], default='У', max_length=1, verbose_name='Стать'),
        ),
        migrations.AddField(
            model_name='product',
            name='consist',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Країна виробництва'),
        ),
        migrations.AddField(
            model_name='product',
            name='warning',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Застереження'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вага'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна зі знижкою'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Основне зображення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Н', 'Немає в наявності'), ('В', 'В наявності'), ('П', 'Під замовлення 2-3 дні'), ('C', 'Скоро в наявності')], default='Н', max_length=1, verbose_name='Статус'),
        ),
    ]
